# Generated by Django 5.2.5 on 2025-10-31 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productlist',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('pname', models.TextField(max_length=40)),
                ('category', models.TextField(max_length=20)),
                ('price', models.IntegerField()),
                ('pimage', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('description', models.TextField(max_length=101)),
            ],
        ),
    ]
