# Generated by Django 5.2.5 on 2025-10-31 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='productlist',
            new_name='product',
        ),
    ]
